language: bash

env:
  NAME: aws-ecr-login

services:
- docker

before_install:
- docker build --no-cache -t engapa/${NAME}:latest .

install:
- docker run -it -d --name ${NAME} engapa/${NAME}:latest

script:
- docker exec -it ${NAME} /bin/bash

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push ${NAME}

after_script:
- docker rm -f ${NAME}